name: Node CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    services:
      mongo:
        image: mongo:4.2.0
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run tests
      run: |
        npm install --unsafe-perm
        npm test
      env:
        CI: true
        NODE_ENV: test
        MONGODB_URI: mongodb://mongo:${{ job.services.mongo.ports[27017] }}/app-test
